# Generated by Django 5.2.12 on 2026-04-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], db_index=True, max_length=10, verbose_name='tipo')),
                ('image', models.ImageField(blank=True, help_text='Subir solo si el tipo es Imagen.', null=True, upload_to='media/images/%Y/%m/', verbose_name='imagen')),
                ('video_file', models.FileField(blank=True, help_text='Subir solo si el tipo es Video y no se usa embed externo.', null=True, upload_to='media/videos/%Y/%m/', verbose_name='archivo de video')),
                ('video_embed_url', models.URLField(blank=True, help_text='URL de embed de YouTube o Vimeo. Alternativa al archivo de video.', verbose_name='URL embed de video')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción para accesibilidad y SEO de imágenes.', max_length=200, verbose_name='texto alternativo')),
                ('caption', models.TextField(blank=True, verbose_name='pie de foto/video')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='ancho (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='alto (px)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='tamaño (bytes)')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'archivo de media',
                'verbose_name_plural': 'archivos de media',
                'ordering': ['-created_at'],
            },
        ),
    ]
