# Generated by Django 5.2.12 on 2026-04-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('domain', models.URLField(help_text='ej: https://agencia-aduanal.loginco.com.mx', verbose_name='dominio')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'sitio destino',
                'verbose_name_plural': 'sitios destino',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('site_targets', models.ManyToManyField(blank=True, related_name='categories', to='blog.sitetarget', verbose_name='sitios destino')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('meta_title', models.CharField(blank=True, help_text='Título para buscadores. Máximo 70 caracteres.', max_length=70, verbose_name='meta título')),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para buscadores. Máximo 160 caracteres.', max_length=160, verbose_name='meta descripción')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas.', max_length=255, verbose_name='palabras clave')),
                ('og_title', models.CharField(blank=True, help_text='Título para redes sociales. Si se deja vacío se usa meta_title.', max_length=95, verbose_name='título Open Graph')),
                ('og_description', models.TextField(blank=True, help_text='Descripción para redes sociales. Si se deja vacío se usa meta_description.', max_length=200, verbose_name='descripción Open Graph')),
                ('canonical_url', models.URLField(blank=True, help_text='URL canónica. Dejar vacío para usar la URL actual.', verbose_name='URL canónica')),
                ('no_index', models.BooleanField(default=False, help_text='Marcar para excluir esta página de los motores de búsqueda.', verbose_name='no indexar')),
                ('schema_markup', models.JSONField(blank=True, default=dict, help_text='Markup estructurado en formato JSON-LD. Se inserta automáticamente en <head>.', verbose_name='JSON-LD Schema.org')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Descripción corta para listados y redes sociales. Máximo 300 caracteres.', max_length=300, verbose_name='resumen')),
                ('body', models.TextField(help_text='Contenido HTML generado por el editor TipTap.', verbose_name='contenido')),
                ('video_url', models.URLField(blank=True, help_text='URL embed de YouTube o Vimeo para incluir en el artículo.', verbose_name='URL de video')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('published', 'Publicado')], db_index=True, default='draft', max_length=15, verbose_name='estado')),
                ('published_at', models.DateTimeField(blank=True, help_text='Dejar vacío para publicar inmediatamente al cambiar estado a Publicado.', null=True, verbose_name='fecha de publicación')),
                ('ai_generated', models.BooleanField(default=False, help_text='Indica si el contenido fue generado o asistido por la IA.', verbose_name='generado con IA')),
                ('reading_time', models.PositiveSmallIntegerField(default=0, help_text='Calculado automáticamente al guardar.', verbose_name='tiempo de lectura (min)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='categoría')),
                ('featured_image', models.ForeignKey(blank=True, limit_choices_to={'file_type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_posts', to='media_manager.mediafile', verbose_name='imagen destacada')),
                ('site_targets', models.ManyToManyField(help_text='Sub-sitio(s) en los que aparecerá esta publicación.', related_name='posts', to='blog.sitetarget', verbose_name='sitios destino')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
