# Generated by Django 5.2.12 on 2026-04-01 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('full_post', 'Artículo completo'), ('meta_only', 'Solo metadatos SEO'), ('excerpt', 'Resumen'), ('improve', 'Mejora de texto'), ('alt_text', 'Texto alternativo')], max_length=20, verbose_name='tipo de generación')),
                ('site_target', models.CharField(blank=True, max_length=100, verbose_name='sitio destino')),
                ('model_used', models.CharField(max_length=100, verbose_name='modelo usado')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens de salida')),
                ('success', models.BooleanField(default=True, verbose_name='exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de generación IA',
                'verbose_name_plural': 'registros de generación IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
